#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew tap d12frosted/emacs-plus
        brew install emacs-plus --without-spacemacs-icon
        # brew install emacs --with-modules --with-librsvg --with-imagemagick --with-gnutls --with-cocoa
        echo "This creates a symlink and not an alias. So Spotlight may not find it (tested on macOS Sierra 10.12.2). Spotlight indexes symlinks to files that are treated as system files, but it doesn’t show them in the GUI. It does show aliases though, so you could just command-option-drag /usr/local/Cellar/emacs-plus/*/Emacs.app to /Applications/ from Finder."
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S make emacs
        elif [[ -f /etc/debian_version ]]; then
            sudo apt-get install -y make emacs
        fi
        ;;
esac

if [[ ! -d "$HOME/.emacs.d" ]]; then
    echo "NO EMACS.D"
    # git clone --recursive "https://github.com/hlissner/.emacs.d" "$HOME/.emacs.d"
fi
