#!/bin/sh

# This needs to be in the home folder and needs
# to be chmod +x so it runs right.

linux_get_bat ()
{
    bf=$(cat $BAT_FULL)
    bn=$(cat $BAT_NOW)
    BAT=`echo "100 * $bn / $bf" | bc`
    echo $BAT
}

freebsd_get_bat ()
{
    echo "$(sysctl -n hw.acpi.battery.life)%"

}

# Do with grep and awk unless too hard

# TODO Identify which machine we're on from teh script.

# add short args
if [ -z $1 ]; then
    # default to charging
    action=1
else
    if [[ $1 == "c" || $1 == "Charging" ]]; then
        # charging
        action=1
    elif [[ $1 == "d" || $1 == "Discharging" ]]; then
        # discharging
        action=0
    fi
fi

if [ -z $2 ]; then
    # default to NO arrow
    arrow=0
else
    if [[ $2 == "a" || $2 == "arrow" ]]; then
        # display arrorw ONLY
        arrow=1
    fi
fi

case $(uname -s) in
    "Linux")
        BATPATH=/sys/class/power_supply/BAT0
        STATUS=$BATPATH/status
        BAT_FULL=$BATPATH/energy_full
        BAT_NOW=$BATPATH/energy_now
        if [ "$1" = `cat $STATUS` -o "$1" = "" ]; then
            echo $(linux_get_bat)%
        fi
        ;;
    "FreeBSD")
        STATUS=`sysctl -n hw.acpi.battery.state`
        case $1 in
            "Discharging")
                if [ $STATUS -eq 1 ]; then
                    freebsd_get_bat
                fi
                ;;
            "Charging")
                if [ $STATUS -eq 2 ]; then
                    freebsd_get_bat
                fi
                ;;
            "")
                freebsd_get_bat
                ;;
        esac
        ;;
    "Darwin")
        case $action in
            # discharging
            0)
                ext="No"
                charge_direction_arrow="▼";;
            # charging
            1)
                ext="Yes"
                charge_direction_arrow="▲";;
        esac

        ioreg -c AppleSmartBattery -w0 | \
        grep -o '"[^"]*" = [^ ]*' | \
        sed -e 's/= //g' -e 's/"//g' | \
        sort | \
        while read key value; do
            case $key in
                "MaxCapacity")
                    export maxcap=$value;;
                "CurrentCapacity")
                    export curcap=$value;;
                "ExternalConnected")
                    if [ "$ext" != "$value" ]; then
                        exit
                    fi
                ;;
                "FullyCharged")
                    if [ "$value" = "!Yes" ]; then
                        exit
                    fi
                ;;
            esac
            if [[ -n "$maxcap" && -n $curcap ]]; then
                if [ $arrow -eq 1 ]; then
                    echo "⮀"
                    exit
                fi

                BAT=`echo "100 * $curcap / $maxcap" | bc`
                echo " "${charge_direction_arrow} ${BAT}%" "
                exit
            fi
        done
esac
