#!/bin/bash
if [ -f /tmp/tmux-layout ]; then
    tmux joinp -t $(cat /tmp/tmux-saved-win-pane)
    tmux select-layout $(cat /tmp/tmux-layout) > /dev/null
    rm /tmp/tmux-max /tmp/tmux-layout
else
    current_pane=$(tmux list-panes | grep '(active)' | cut -d : -f 1)
    current_win=$(tmux list-windows | grep '(active)' | cut -d : -f 1)
    layout=$(tmux list-windows | grep '(active)' | cut -d ' ' -f 5 | rev | cut -b 2- | rev)
    pane_num=$(tmux list-panes | wc -l)

    [ $pane_num -eq 1 ] && exit 0;
    [ $current_pane -eq 1 ] && pane=1 || pane=$(expr $current_pane - 1)

    echo ${current_win}.${pane} > /tmp/tmux-saved-win-pane
    echo $layout > /tmp/tmux-layout

    tmux breakp
fi
