#!/usr/bin/env sh

# Copyright (c) 2012 Brandon Orther <AbleCoder@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#
# NAME
#   tmux-split-win-cwd -- tmux split-window with current working dir
#
# SYNOPSIS
#   tmux-split-win-cwd [-dhvP] [-i] [-p percentage|-l size] [-t target-pane]
#
#   NOTE: All options match tmux split-window except those noted below.
#
#   -i
#      Inverse default split direction. For example if you split vertically by
#      (by passing -v) the default behavior is to create a new pane below and if
#      you spit horizontally (by passing -h) the default behavior is to create a
#      new pane to the right. With the -i argument passed the pane will be
#      created in the opposite of the default direction. So -v -i will create a
#      new pane above and -h -i will create a new pane to the left.
#
#      NOTE: The inversion of direction is created by running a swap-pane after
#            creating the new pane.
#
#   [command]
#     REMOVED - The optional split-window [command] argument is removed.
#
# DESCRIPTION
#   This script creates a new tmux pane by splitting a window and setting the
#   new pane's path to the current working dir of the shell that calls it.
#
#   Useful for creating splits in tmux windows designated for a specific project.
#   Instead of having to `cd` from the path that tmux was started at to the path
#   of the window you create the pane from, this script automatically changes the
#   new pane's path.


#
# INSTALL AND USAGE
#
# 1. Download this script to your how folder and give it permissions to execute:
#
#   $ wget https://raw.github.com/AbleCoder/dotfiles/master/tmux/tmux-split-win-cwd -O ~/tmux-split-win-cwd
#   $ chmod +x ~/tmux-split-win-cwd
#
# 2. Split window and test new pane's cur dir
#
#   (in tmux window shell)
#   $ cd /
#   $ ~/tmux-split-win-cwd -v
#
#   (in new tmux pane shell, should output: /)
#   $ pwd
#
#
# MY PERSONAL TMUX SPLIT WINDOW BINDINGS
#
#   Add the following bindings to your ~/.tmux.conf:
#
#      bind | send-keys " ~/tmux-panes -h" C-m
#      bind - send-keys " ~/tmux-panes -v; tmux swap-pane -U" C-m
#      bind _ send-keys " ~/tmux-panes -v" C-m
#
#   With the above bindings you get the following split behaviors:
#
#      <prefix>+| (Create new pane to the right)
#      <prefix>+- (Create new pane above)
#      <prefix>+_ (Create new pane below)
#

set -o nounset

TMUX_CURRENT_DIR=`pwd`
tmux split-window $* "cd ${TMUX_CURRENT_DIR}; ${SHELL}"
