#!/bin/bash

#-------------------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------------------

# cli pane location - D, L, R, or U
CFG_CLI_LOCATION="D"

# cli pane size (in percent)
CFG_CLI_SIZE_X=0
CFG_CLI_SIZE_C=25
CFG_CLI_SIZE_V=70
CFG_CLI_SIZE_B=95

#-------------------------------------------------------------------------------
# THAT HOT SHIT CODE BELOW
#-------------------------------------------------------------------------------

# defaults
_cli_open_size=$CFG_CLI_SIZE_X
_cli_open_direction_flag="-v"
_cli_resize_smaller_direction_flag="-D"
_cli_resize_bigger_direction_flag="-U"
tmux_border_size=3

# cli location flags
case $CFG_CLI_LOCATION in
  D)
    _cli_open_direction_flag="-v"
    _cli_resize_smaller_direction_flag="-D"
    _cli_resize_bigger_direction_flag="-U"
    ;;
  L)
    _cli_open_direction_flag="-h"
    _cli_resize_smaller_direction_flag="-L"
    _cli_resize_bigger_direction_flag="-R"
    ;;
  R)
    _cli_open_direction_flag="-h"
    _cli_resize_smaller_direction_flag="-R"
    _cli_resize_bigger_direction_flag="-L"
    ;;
esac

# parse options
while getopts ":xcvb" opt; do
  case $opt in
    x)
      _cli_open_size=$CFG_CLI_SIZE_X
      ;;
    c)
      _cli_open_size=$CFG_CLI_SIZE_C
      ;;
    v)
      _cli_open_size=$CFG_CLI_SIZE_V
      ;;
    b)
      _cli_open_size=$CFG_CLI_SIZE_B
      ;;
  esac
done

# open cli pane if necessary
num_panes=$(tmux list-panes | wc -l)
if [ $num_panes -eq 1 ]; then
  # no other panes exist so we create one (for the cli)

  # tmux 1.6 split
  #~/tmux-split-win-cwd -v -p 1

  # switch back to vim pane before exiting
  #tmux select-pane -U

  # tmux 1.7 split
  tmux split-window $_cli_open_direction_flag -d

  exit
fi

# pull current pane info
cur_pane=$(tmux list-panes | grep '(active)' | cut -d : -f 1)
cur_pane_height=$(tmux list-panes | grep '(active)' | cut -d ] -f 1 | cut -d x -f 2)
cur_pane_width=$(tmux list-panes | grep '(active)' | cut -d [ -f 2 | cut -d x -f 1)
cur_win=$(tmux list-windows | grep '(active)' | cut -d : -f 1)
cur_win_height=$(tmux list-windows | grep '(active)' | cut -d ] -f 1 | cut -d [ -f 2 | cut -d x -f 2)
cur_win_width=$(tmux list-windows | grep '(active)' | cut -d [ -f 2 | cut -d x -f 1)

# get new cli height in lines
new_cli_height_lines=$((($_cli_open_size * $cur_win_height) / 100))
new_cli_width_lines=$((($_cli_open_size * $cur_win_width) / 100))

# minimize cli before opening
tmux resize-pane $_cli_resize_smaller_direction_flag 1000

# only open cli pane if more than 0 size
if [ $_cli_open_direction_flag == "-v" ]; then
  if [ $new_cli_height_lines -gt 0 ]; then
      # open cli to calculated height
      tmux resize-pane $_cli_resize_bigger_direction_flag $new_cli_height_lines
  fi
else
  if [ $new_cli_width_lines -gt 0 ]; then
      # open cli to calculated width
      tmux resize-pane $_cli_resize_bigger_direction_flag $new_cli_width_lines
  fi
fi

# old toggle open functionality
################################
## get cli height (only works if only 2 horizontal panes)
#cli_height=$(($cur_win_height - $cur_pane_height - $tmux_border_size))
#
## toggle cli open/close
#if [ $cli_height -lt $_cli_open_size ]; then
#  # open cli pane
#  cli_height_diff=$(($_cli_open_size - $cli_height))
#  tmux resize-pane -U ${cli_height_diff}
#else
#  # close cli pane
#  tmux resize-pane -D 1000
#fi
