#!/bin/bash

#-------------------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------------------

cfg_cli_open_size=20 # number of lines

#-------------------------------------------------------------------------------
# THAT HOT SHIT CODE BELOW
#-------------------------------------------------------------------------------

tmux_border_size=3
num_panes=$(tmux list-panes | wc -l)

# open cli pane if necessary
if [ $num_panes -eq 1 ]; then
  # no other panes exist so we create one (for the cli)
  ~/tmux-panes -v

  # fill new cli pane with blank prompts (hides ~/tmux-panes cd and clear cmds)
#  COUNTER=0
#  while [  $COUNTER -lt $cfg_cli_open_size ]; do
#    tmux send-keys "clear" C-m
#    let COUNTER=COUNTER+1 
#  done

  # switch back to vim pane before resizing
  tmux select-pane -U
fi

# pull current pane and window sizes
cur_pane=$(tmux list-panes | grep '(active)' | cut -d : -f 1)
cur_pane_height=$(tmux list-panes | grep '(active)' | cut -d ] -f 1 | cut -d x -f 2)
cur_win=$(tmux list-windows | grep '(active)' | cut -d : -f 1)
cur_win_height=$(tmux list-windows | grep '(active)' | cut -d ] -f 1 | cut -d [ -f 2 | cut -d x -f 2)

# get cli height (only works if only 2 horizontal panes)
cli_height=$(($cur_win_height - $cur_pane_height - $tmux_border_size))

# toggle cli open/close
if [ $cli_height -lt $cfg_cli_open_size ]; then
  # open cli pane
  cli_height_diff=$(($cfg_cli_open_size - $cli_height))
  tmux resize-pane -U ${cli_height_diff}
else
  # close cli pane
  tmux resize-pane -D 1000
fi
