#!/bin/bash

#-------------------------------------------------------------------------------
# CONFIG
#-------------------------------------------------------------------------------

# cli pane size (in number of lines)
cfg_cli_open_size=30
cfg_cli_open_big_size=40

#-------------------------------------------------------------------------------
# THAT HOT SHIT CODE BELOW
#-------------------------------------------------------------------------------

# defaults
_cli_open_size=$cfg_cli_open_size
tmux_border_size=3

# parse options
while getopts ":b" opt; do
  case $opt in
    b)
      # set cli open size big
      _cli_open_size=$cfg_cli_open_big_size
      ;;
  esac
done

# open cli pane if necessary
num_panes=$(tmux list-panes | wc -l)
if [ $num_panes -eq 1 ]; then
  # no other panes exist so we create one (for the cli)

  # tmux 1.6 split
  #~/tmux-split-win-cwd -v -p 1

  # tmux 1.7 split
  tmux split-window -v -d

  # switch back to vim pane before exiting
  #tmux select-pane -U

  exit
fi

# pull current pane info
cur_pane=$(tmux list-panes | grep '(active)' | cut -d : -f 1)
cur_pane_height=$(tmux list-panes | grep '(active)' | cut -d ] -f 1 | cut -d x -f 2)
cur_win=$(tmux list-windows | grep '(active)' | cut -d : -f 1)
cur_win_height=$(tmux list-windows | grep '(active)' | cut -d ] -f 1 | cut -d [ -f 2 | cut -d x -f 2)

# get cli height (only works if only 2 horizontal panes)
cli_height=$(($cur_win_height - $cur_pane_height - $tmux_border_size))

# toggle cli open/close
if [ $cli_height -lt $_cli_open_size ]; then
  # open cli pane
  cli_height_diff=$(($_cli_open_size - $cli_height))
  tmux resize-pane -U ${cli_height_diff}
else
  # close cli pane
  tmux resize-pane -D 1000
fi
